# Generated by Django 3.1.6 on 2021-02-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210212_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shippingCost',
            new_name='shipping_cost',
        ),
    ]
